### ISSUE TITLE
Larger user base? 

### ISSUE THREAD

**Issue by mmoayyed** [jtgasper3/docker-images#2]
Please expand the ldif file to include more sample users. I'd say 10-15 is a pretty good number. This is useful for perf tests against the shib idp or CAS.

**Comment by jtgasper3** [comment]
Personally, I like it small because it is easier to add lots than remove
even a few...

If I might make a recommendation... use this image as a base. Then ADD this
file:
https://github.com/UniconLabs/grouper-demo-docker/blob/master/seed-data/users.ldif

Next, use the appropriate commands to start up the ldap server, and import
the users.ldif within the local docker file.

```
RUN service slapd start \
    && ldapadd -Y EXTERNAL -H ldapi:/// -f eduPerson.schema \
    && ldapadd -H ldapi:/// -f users.ldif -x -D
"cn=admin,dc=example,dc=edu" -w password 1>/dev/null
```

 The benefit to this is you can tailor your use accounts to match specific
needs, like adding eduPersonProperties, etc. Speaking of which the
grouper-demo-docker project also has an OpenLDAP/slapd eduPersonSchema
ready to be added and imported as well.
